define visibility class API
TCDSolar/xrayvision pull request #55
Opened 2024-04-29 16:27 UTC by annavolp

This pull request defines a new object for visibilities and its API.

2024-04-30 14:02 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +    def __init__(self, visibilities, *, u, v, names, uncertainty=None, meta=None):
I think this is what we need to make sure all the inputs are the correct types.  We should confirm this is correct though.

```suggestion
    @apu.quantity_input()
    def __init__(self,
                 visibilities: apu.Quantity,
                 *,
                 u: apu.Quantity[1/apu.arcsec],
                 v: apu.Quantity[1/apu.arcsec],
                 names: Iterable[str],
                 uncertainty: Any = None,
                 meta=None):
```

2024-05-07 11:40 UTC, DanRyanIrish commented
@annavolp Can you push your latest work including the tests you wrote in Dublin?

2024-05-21 11:18 UTC, DanRyanIrish requested changes

2024-05-21 11:18 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +        coords: dict = {},
```suggestion
        coords: dict = {}
```

2024-05-21 11:18 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +        coords: dict = {},
```suggestion
        coords: dict = {}
```

2024-05-21 11:21 UTC, DanRyanIrish requested changes

2024-05-21 11:21 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +        uncertainty: Union[apu.Quantity, None],
```suggestion
        uncertainty: Union[apu.Quantity, None] = None,
```

2024-05-21 11:21 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +        uncertainty: Union[apu.Quantity, None],
```suggestion
        uncertainty: Union[apu.Quantity, None] = None,
```

2024-05-22 12:09 UTC, DanRyanIrish commented
If we agree that #62 is ready to be merged now, it probably makes sense to combined that PR into this one first and then merge both Anna and my contributions together.  I think we're basically there.  Of course, small changes can still be made in the future if we want.

2024-05-24 07:41 UTC, DanRyanIrish approved these changes

2024-05-24 07:41 UTC, DanRyanIrish commented
@samaloney This is ready to merge.

2024-05-24 07:48 UTC, DanRyanIrish requested changes

2024-05-24 07:48 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +_E_RANGE_KEY = "energy_range"
```suggestion
_E_RANGE_KEY = "spectral_range"
```

2024-05-24 07:48 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +        Energy range over which the visibilities are computed.
```suggestion
    def spectral_range(self) -> Union[Iterable[apu.Quantity], None]:
        """
        Spectral range over which the visibilities are computed.
```

2024-05-24 07:48 UTC, DanRyanIrish commented on xrayvision/visibility.py
> +    def energy_range(self):
```suggestion
    def spectral_range(self):
```

2024-05-24 07:50 UTC, DanRyanIrish commented
@samaloney Actually last minute change.  We should make "energy" "spectral".

2024-05-24 10:12 UTC, samaloney approved these changes

2024-05-24 10:15 UTC, merged